name: Release

on:
  release:
    types: [published]
jobs:
  tarball-info:
    # h/t https://stackoverflow.com/a/74189403/1241736
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Determine URL
        run: echo "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz"
      - name: Determine SHA256
        run: curl -sL "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz" | shasum -a 256 | cut -d " " -f 1